name: Dependency review

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Check for vulnerable dependencies
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
